### ISSUE TITLE
Typo in blend.py

### ISSUE THREAD

**Issue by NejcCoz** [EarthObservation/RVT_py#13]
Is there a typo in the following line? The problem with how the brackets are placed for the second boolean expression.

https://github.com/EarthObservation/RVT_py/blob/0db4755e2ca544979b20c44867c41561700370bd/rvt/blend.py#L585

I am not sure what are the consequences of this, but I feel like it could affect blending., because it doesn't preform a check for values that are greater than 1.

**Comment by zm8597** [comment]
Sorry for my bad response time. Yes it is a typo :), I will fix it. Thank you.
