### ISSUE TITLE
System dependent path string

### ISSUE THREAD

**Issue by MattPainter01** [EarthObservation/RVT_py#14]
Hey, Big fan of your library! 

When trying to run a blend, I found that I had to change this line to use linux file separators.

https://github.com/EarthObservation/RVT_py/blob/4d212b414cebe3112854654c8195a020c7d9ccdc/rvt/blend.py#L356

I think everywhere else you use `os.path.join(...)` to get system independent paths. Thought I should point this one out! 

I'm happy to put in a PR with this change if you like.

**Comment by zm8597** [comment]
Hey 😃, thank you very much for bringing that up! I will fix it right now. We really appriciate bug reports.
